name: check-solution-existence

description: check-solution-existence

inputs:
  solution_name:
    description: solution_name
    required: true
  environment_url:
    description: environment_url
    required: true
  tenant_id:
    description: tenant_id
    required: true
  client_id:
    description: client_id
    required: true
  client_secret:
    description: client_secret
    required: true

runs:
  using: "composite"
  steps:
    - uses: nuget/setup-nuget@v1
      with:
        nuget-version: '5.x'
    - name: install-pac-cli-nugget
      run: nuget install Microsoft.PowerApps.CLI
      shell: pwsh
