name: check-solution-existence

description: check-solution-existence

inputs:
  secrets:
    description: "environment secrets"
    required: true

runs:
  using: "composite"
  steps:
    - uses: Firenza/secrets-to-env@v1.1.0
      with:
        secrets: ${{ inputs.secrets }}
    - uses: nuget/setup-nuget@v1
      with:
        nuget-version: '5.x'
    - name: install-pac-cli-nugget
      run: |
        nuget install Microsoft.PowerApps.CLI -OutputDirectory pac
        $nugetFolder = Get-ChildItem "pac" | Where-Object {$_.Name -match "Microsoft.PowerApps.CLI."}
        $pacFolder = $nugetFolder.FullName + "\tools"
        echo $pacFolder
        $test = "$pacFolder\pac.exe auth create --url ${{ inputs.environment_url }}"
        echo $test
      shell: powershell
