name: pva-workflow-2
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "GitHub environment name to get the solution"
        required: true
        default: "DEV"
env:
  workflow_scripts_path: .github/workflows/scripts

jobs:
  execute-pva-workflow-1:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - uses: actions/checkout@v2
      - name: check-branch-existence
        continue-on-error: true
        id: check-branch-existence
        uses: actions/github-script@v5
        with:
          github-token: ${{secrets.WORKFLOW_DISPATCH_TOKEN}}
          script: |
            let branch = await github.rest.git.getRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'heads/${{ secrets.BRANCH_TO_CREATE }}'
            })

            if (branch.data != null)
            {
              await github.rest.git.deleteRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: 'heads/${{ secrets.BRANCH_TO_CREATE }}'
              })
            }

