name: pva-workflow-1
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "GitHub environment name to get the solution"
        required: true
        default: "DEV"
env:
  workflow_scripts_path: .github/workflows/scripts
  commit_message: "default commit message"

jobs:
  export-unpack-commit-solution:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - uses: actions/checkout@v3
      - name: check-branch-existence
        id: check-branch-existence
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.WORKFLOW_DISPATCH_TOKEN}}
          script: |
            let branch = await github.rest.git.listMatchingRefs({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'heads/${{ secrets.BRANCH_TO_CREATE }}'
            })

            if (branch.data.length > 0) {
              await github.rest.git.deleteRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: 'heads/${{ secrets.BRANCH_TO_CREATE }}'
              })
            }

      - name: exec-export-unpack-commit-solution-workflow
        id: exec-export-unpack-commit-solution-workflow
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.WORKFLOW_DISPATCH_TOKEN}}
          script: |
            let sleep = require('${{ env.workflow_scripts_path }}/js/Sleep.js')
            let ref = '${{ github.ref }}'
            let params = {
              solution_name: '${{ secrets.SOLUTION_NAME }}',
              environment_url: '${{ secrets.ENVIRONMENT_URL }}',
              source_branch: '${{ secrets.SOURCE_BRANCH }}',
              branch_to_create: '${{ secrets.BRANCH_TO_CREATE }}',
              commit_message: '${{ env.commit_message }}'
            }
            sleep.dispatchWorkflow(github, context, 'export-unpack-commit-solution.yml', ref, params)

      - name: check-workflow-status
        id: check-workflow-status
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.WORKFLOW_DISPATCH_TOKEN}}
          script: |
            let sleep = require('${{ env.workflow_scripts_path }}/js/Sleep.js')
            await sleep.checkworkflow(github, context, 'export-unpack-commit-solution.yml')