name: pvawf4-deploy-tagged-solution-to-environment
on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        description: "GitHub tag for solution-version to deploy"
      environment:
        required: true
        description: "GitHub environment name to deploy the solution"
        default: PRD
env:
  workflow_scripts_path: .github/workflows/scripts

jobs:
  trigger-deploy-tagged-solution:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: deploy-tagged-solution-to-environment
        id:  deploy-tagged-solution-to-environment
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.WORKFLOW_DISPATCH_TOKEN}}
          script: |
            let helper = require('${{ env.workflow_scripts_path }}/js/githubHelper.js')
            let ref = '${{ github.ref }}'
            let params = {
              tag: '${{ github.event.inputs.tag }}',
              environment: '${{ github.event.inputs.environment }}'
            }
            await helper.dispatchWorkflow(github, context, 'deploy-tagged-solution-to-environment.yml', ref, params)

      - name: check-workflow-status
        id: check-workflow-status
        uses: actions/github-script@v6
        with:
          script: |
            let helper = require('${{ env.workflow_scripts_path }}/js/githubHelper.js')
            await helper.checkWorkflowStatus(github, context, core, 'deploy-tagged-solution-to-environment.yml')
