name: pvawf2-sync-from-main
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "GitHub environment name to get the solution"
        required: true
        default: "DEV"
env:
  workflow_scripts_path: .github/workflows/scripts

jobs:
  execute-pvawf1-export-unpack-commit-solution-workflow:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - uses: actions/checkout@v2
      - name: run-pvawf1-export-unpack-commit-solution-workflow
        id: run-pvawf1-export-unpack-commit-solution-workflow
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.WORKFLOW_DISPATCH_TOKEN}}
          script: |
            let helper = require('${{ env.workflow_scripts_path }}/js/githubHelper.js')
            let ref = '${{ github.ref }}'
            let params = {
              environment: '${{ github.event.inputs.environment }}',
            }
            await helper.dispatchWorkflow(github, context, 'pvawf1-export-unpack-commit-solution-workflow.yml', ref, params)

      - name: check-pvawf1-export-unpack-commit-solution-workflow-status
        id: check-pvawf1-export-unpack-commit-solution-workflow-status
        uses: actions/github-script@v6
        with:
          script: |
            let helper = require('${{ env.workflow_scripts_path }}/js/githubHelper.js')
            await helper.checkWorkflowStatus(github, context, core, 'pvawf1-export-unpack-commit-solution-workflow.yml')

  sync-from-main-branch:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    needs: execute-pvawf1-export-unpack-commit-solution-workflow
    steps:
      - uses: actions/checkout@v2
      - name: sync-from-main
        id: sync-from-main
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.WORKFLOW_DISPATCH_TOKEN}}
          script: |
            let helper = require('${{ env.workflow_scripts_path }}/js/githubHelper.js')
            let ref = '${{ github.ref }}'
            let params = {
              from_branch: '${{ secrets.SOURCE_BRANCH }}',
              to_branch: '${{ secrets.BRANCH_TO_CREATE }}'
            }
            await helper.dispatchWorkflow(github, context, 'sync-from-main.yml', ref, params)

      - name: check-sync-from-main-workflow-status
        id: check-sync-from-main-workflow-status
        uses: actions/github-script@v6
        with:
          script: |
            let helper = require('${{ env.workflow_scripts_path }}/js/githubHelper.js')
            await helper.checkWorkflowStatus(github, context, core, 'sync-from-main.yml')
