name: sync-from-main
on:
  workflow_dispatch:
    inputs:
      from_branch:
        description: "The ref (branch, commit, tag) that you want to import"
        required: true
        default: main
      to_branch:
        description: "branch"
        required: false

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    name: Syncing from main branch
    steps:
      - name: compare-head-with-base-branch
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.WORKFLOW_DISPATCH_TOKEN}}
          script: |
            let res = null;
            try {
              res = await github.rest.pulls.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                head: '${{ github.event.inputs.from_branch }}',
                base: '${{ github.event.inputs.to_branch }}',
                title: '[PR] ${{ github.event.inputs.from_branch }} into ${{ github.event.inputs.to_branch }}'
              })

              console.log(res)
            }
            catch (err) {
              console.log(res)
            }
