name: test
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "GitHub environment name to get the solution"
        required: true
        default: "DEV"
env:
  workflow_scripts_path: .github/workflows/scripts

jobs:
  build-deploy-solution:
    runs-on: windows-2022
    environment: ${{ github.event.inputs.environment }}
    steps:
      - uses: actions/checkout@v2

      - name: check-solution
        uses: ./.github/actions/check-solution-existence
        with:
          solution_name: ${{ secrets.SOLUTION_NAME }}
          environment_url: ${{ secrets.ENVIRONMENT_URL }}
          tenant_id: ${{ secrets.TENANT_ID }}
          app_id: ${{ secrets.CLIENT_ID }}
          client_secret: ${{ secrets.CLIENT_SECRET }}
          secrets: ${{ toJSON(secrets) }}