name: test
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "GitHub environment name to get the solution"
        required: true
        default: "DEV"
env:
  workflow_scripts_path: .github/workflows/scripts
  commit_message: "default commit message"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: check-env-existence
        id: check-env-existence
        uses: actions/github-script@v5
        with:
          github-token: ${{secrets.WORKFLOW_DISPATCH_TOKEN}}
          script: |
            let res = await github.rest.repos.getAllEnvironments({
              owner: context.repo.owner,
              repo: context.repo.repo
            })

            if (res.data.environments.length > 0) {
              if (!res.data.environments.find(env => env.name === '${{ github.event.inputs.environment }}')) {
                core.setFailed('environment does not exists')
              }
            }
